# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0002_calificacion_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='tipo_doc',
            field=models.CharField(choices=[('DNI', 'Documento Nacional de Identidad'), ('LE', 'Libreta de enrolamiento'), ('PS', 'Pasaporte')], default='DNI', max_length=3),
            preserve_default=False,
        ),
    ]
