# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0004_auto_20170615_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nombre',
            field=models.CharField(default='Primer curso', max_length=40),
            preserve_default=False,
        ),
    ]
