# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0006_curso_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='anio_ingreeo',
            new_name='anio_ingreso',
        ),
        migrations.AddField(
            model_name='alumno',
            name='numero_folio',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
