# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0010_alumno_egreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='materias',
        ),
        migrations.AddField(
            model_name='materia',
            name='docente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='escuela.Docente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='nombre',
            field=models.CharField(default='nombrecillo', max_length=50),
            preserve_default=False,
        ),
    ]
