# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0011_auto_20170711_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='cuil',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
