# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0012_docente_cuil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='licencia',
        ),
        migrations.AddField(
            model_name='docente',
            name='estado',
            field=models.CharField(default='activo', max_length=10),
        ),
        migrations.AddField(
            model_name='docente',
            name='fecha_licencia_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='fecha_licencia_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='fecha_suspendido_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='fecha_suspendido_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='tipo_licencia',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
