# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0013_auto_20170711_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='escuela.Plan'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='escuela.Curso'),
        ),
    ]
