# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0015_auto_20170713_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='foto',
            field=models.BooleanField(default=False),
        ),
    ]
