# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0016_alumno_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(blank=True, default='Activa', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado_pase',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
