# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 01:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0017_auto_20170718_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='tipo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(blank=True, default='Confirmada', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado_pase',
            field=models.CharField(blank=True, default='No aplica', max_length=30, null=True),
        ),
    ]
