# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0018_auto_20170719_0122'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together=set([('curso', 'materia', 'alumno', 'tipo')]),
        ),
    ]
