# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 01:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0019_auto_20170719_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
