# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0020_auto_20170719_0139'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together=set([('curso', 'alumno')]),
        ),
    ]
