# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0021_auto_20170720_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='numero_doc',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='escuela.Materia'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='numero_doc',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
