# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0025_auto_20170723_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(default='Por defecto', max_length=50),
            preserve_default=False,
        ),
    ]
